# Site settings
title: Alan Ng
email: alanng95@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a Web Developer/UX Designer currently residing in Sydney, Australia. 
  I'm focused in developing JavaScript and Ruby on Rails web apps. Feel free
  to visit me at my Twitter, Linkedin, and GitHub. I'm always at meetups throughout Sydney,
  so feel free to say hello!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alan.ng" # the base hostname & protocol for your site
twitter_username: HomemadeIcing
github_username:  HomemadeIcing

# Build settings
markdown: rdiscount

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']